const route = require("express").Router()
const user = require("../controller/user")
const post = require("../controller/update_profile")
const verify = require("../middleware/user")
route.post("/reg",user.reg)
route.post("/log",user.log)
route.post("/post",post.create)
route.get("/post_get",post.get)
route.delete("/post_del/:id",post.delpost)
route.put("/update_post/:id",post.update_post)
route.put("/profile",user.profile)
route.get("/check",verify,user.check)
route.get("/logout",user.logout)
route.put("/Adv_update",verify,user.Adv_update)
module.exports = route;